sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
env:
  global:
    - PATH="/usr/bin:$PATH"

# before_script:
#   # Pull container.
#   - 'docker pull hhercules/docker-${distro}-ansible:latest'

before_install:
    # Ansible doesn't play well with virtualenv
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine

install:
  - sudo pip install docker-py
    # software-properties-common for ubuntu 14.04
    # python-software-properties for ubuntu 12.04
  - sudo apt-get install -y sshpass software-properties-common python-software-properties
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible
  - sudo rm /usr/bin/python && sudo ln -s /usr/bin/python2.7 /usr/bin/python
  - ansible --version

script:
  - file=`git show --name-only --oneline "${TRAVIS_COMMIT}" | tail -n1 `
  - role=`git show --name-only --oneline "${TRAVIS_COMMIT}" | tail -n1 | awk -F'/' '{print $2}'`
  - echo "${role}"
  - if [ $file == ".travis.yml" ] || [ -z $role ] ; then echo "no role changes"; exit 0; else if [ "${TRAVIS_BRANCH}" == "master" ]; then for r in $(ls roles); do ansible-playbook roles/$r/test/test.yml; done; else ansible-playbook roles/${role}/test/test.yml --syntax-check; ansible-playbook roles/${role}/test/test.yml; fi
; fi
