- name: Bring up list of hosts
  local_action:
    module: docker
    name: "{{ item['name'] }}"
    image: "{{ item.image|default(provision_docker_image_default) }}"
    privileged: "{{ provision_docker_privileged }}"
    state: "{{ provision_docker_state }}"
    stop_timeout: 120
    tty: "{{provision_docker_use_docker_connection | bool}}"
    expose:
      - "1-65535"
    command: tail -f /dev/null
  register: docker_ins
  with_items: "{{ provision_docker_inventory }}"

- block:
  # TODO: copy ALL host vars in the inventory
  - name: "Associate ip address with hosts"
    local_action:
      module: add_host
      name: "{{ item.1['name'] }}"
      # container_id: "{{ provision_docker_id.results[item.0].stdout }}"
      ansible_connection: docker
      ansible_ssh_user: "root"
      ansible_become_user: "root"
      ansible_become: "yes"
      groups: "{{ provision_docker_groups | union(item.1['groups']|default([])) | join(',') }}"
    with_indexed_items: "{{ provision_docker_inventory }}"
    changed_when: false
