---
galaxy_info:
  author: Chris Meyers
  description: Ansible iptables role for RH
  company: Ansible
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.9.2
  platforms:
  - name: EL
    versions:
    - 6
  #  - 7
  categories:
  #- cloud
  #- cloud:ec2
  #- cloud:gce
  #- cloud:rax
  #- clustering
  #- database
  #- database:nosql
  #- database:sql
  #- development
  #- monitoring
  - networking
  #- packaging
  #- system
  #- web
dependencies: []
  
